# Generated by Django 3.1.4 on 2021-07-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('variety', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('discount_Amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pet_log',
            },
        ),
    ]
